### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by alfidhadiat** [xdssio/goldilox#14]
# Vaex First
Typo: "Vaex is an open-soruce..."
Fix: "Vaex is an open-source"

Typo: "...to allow the extreme flexibility for advance pipeline solutions..."
Fix: "...to allow the extreme flexibility for advanced pipeline solutions..."

# Best Practices
## Add columns!
Typo: "...for every value tou would want..."
Fix: "...for every value you would want..."

Typo: "...which explain the XGBoost prediction."
Fix: "...which explains the XGBoost prediction."

Typo: "..., prediciton with distance (for confidance) etc,."
Fix: "..., prediction with distance (for confidence) etc,."

## DataFrames
Typo: "In production, this allow you do make sure you... and passthrough elements you..."
Fix: "In production, this allows you to make sure you... and pass through elements you..."

## Big Data -> Vaex
Typo: "Vaex is excellent for big data - lazy evlaution...
Fix: "Vaex is excellent for big data -- lazy evaluation..."

## Variables and description
Typo: "... - any constant you what the backend/frontend could query."
Fix: "... - any constant you want, the backend/frontend could query." -> assuming this is the sentence you were going for

# Advance -> Fix: "Advanced"
### sklearn_vs_vaex_vs_pyspark.ipynb
Typo: "..., you should give her a rise!"
Fix: "..., you should give her a raise!"

### ensemble_example.ipynb
Typo: "Crazy ensmble logic example"
Fix: "Crazy ensemble logic example"

# Data science examples
## Vaex Skleran Predictor -> Vaex Sklearn Prediction
Typo: "The predictor can apply any skleran..."
Fix: "The predictor can applly any sklearn..."

### lightgbm.ipynb
Typo: "Variebels and description"
Fix: "Variables and description"

Typo: "...which want to assosiate..."
Fix: "...which want to associate..."

Typo: "A greate place..."
Fix: "A great place..."

**Comment by xdssio** [comment]
Done, Thanks!
